dist: trusty
sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  slack:
    secure: fZm+zCC391+EzUc2FprOO/MVtvfXjhizt0EXNX4aRWwZnPkkmpiqfdZ1XCx5BslsDw5ExvTT5UGyDCXqMbigJ+dVVEdGb5ENW/NG+6o7/0//fKWx47xMIkgnbxKR6oKHhS45g8hu6KpyTUXhkR5ANmWW2SteRE1O8/QQwvOE+V6YkQd4MEK1VHPJhnwybOBDKAZqgfxNRitOwa0xXxM1hRKK5mt1grAtdh+F4y/0GdjDVORugfk/115cnlRjONEHrk1f5QMLxXBF/Q/Nl2UPSqeYUUsJPwooEFU68qN0r0Ddwua+BCeYMVgKsgqAGbCj0ySj86akG0ihyKLLSk0sLbMn5PmdI+5OQcMu+JZUebYiK/+uxzem1NrU6VVRi8jiErKWnNv3qwPvB+NUX2Ny3gfg7cn4AQfqKdqvJzJRjB0kY6keHLLr8+oAsTOD2wGB2hPG+oy8lg9LpkFJIvcZfOmJKaa+yNSJHIEm5cjpWreFOhOms69U2cwjpDEmC0EfkILmmPmFfyhlws+BWSObsZLFkgAjJt2QvMnBPht2H+BPDLQW1VfzF+bRuL3F0ItIXVOFjMtum5Oz8GPWUJqK8FymyQAqlfXGmUI/XYeFR5qc9/QBWvKAoSXBwVxS6LbwWkptN3tg0I9DiztjHpGtgtT+IPiDXpfKq+nZRUeRFWo=
